Web/MvcTemplate.Web/Controllers/BooksController.cs
namespace MvcTemplate.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using MvcTemplate.Common.Mapping;
    using MvcTemplate.Services.Data;
    using MvcTemplate.Web.ViewModels.Home;
    using X.PagedList;

    [Authorize]
    public class BooksController : BaseController
    {
        private IBookService books;
        private ICategoryService bookCategories;
        private IPageService pages;

        public BooksController(
            IBookService books,
            ICategoryService bookCategories,
            IPageService pages)
        {
            this.books = books;
            this.bookCategories = bookCategories;
            this.pages = pages;
        }

        public ActionResult ById(string id, int? page, int? absolutePageNumber)
        {
            var book = this.books.GetById(id);
            var bookViewModel = AutoMapperConfig.Configuration.CreateMapper().Map<BookReadViewModel>(book);

            var viewModel = new ReadViewModel();
            viewModel.Book = bookViewModel;
            var allPages = this.pages.GetAllPages(book.Id);
            var firstPageId = allPages.First().Id;

            var products = allPages.Select(x => x.HtmlContent); //returns IQueryable<Product> representing an unknown number of products. a thousand maybe?

            var pageNumber = page ?? 1; // if no page was specified in the querystring, default to the first page (1)
            var onePageOfProducts = products.ToPagedList(pageNumber, 1); // will only contain 25 products max because of the pageSize
            if (absolutePageNumber != null)
            {
                viewModel.Page = allPages.First(x => x.Id == absolutePageNumber);
            }
            else
            {
                viewModel.Page = allPages.First(x => x.Id == firstPageId + pageNumber - 1);
            }

            this.ViewBag.OnePageOfProducts = onePageOfProducts;

            return this.View(viewModel);
        }

        [AllowAnonymous]
        public ActionResult Review(string id)
        {
            var book = this.books.GetById(id);
            var viewModel = AutoMapperConfig.Configuration.CreateMapper().Map<BookViewModel>(book);
            return this.View(viewModel);
        }

        [AllowAnonymous]
        public ActionResult AllBooks(string categoryName, string search)
        {
            var bookList = new List<BookViewModel>();
            if (categoryName != null)
            {
                bookList = this.books.GetAllBooks().Where(x => x.Category.Name == categoryName).To<BookViewModel>().ToList();
            }
            else if (search != null)
            {
                bookList = this.books.GetAllBooks().Where(x => x.Title.ToLower().Contains(search.ToLower())).To<BookViewModel>().ToList();
            }
            else
            {
                bookList = this.books.GetAllBooks().To<BookViewModel>().ToList();
            }

            var categories =
                this.Cache.Get("categories", () => this.bookCategories.GetAll().To<BookCategoryViewModel>().ToList(), 30 * 60);

            var viewModel = new AllBooksViewModel
            {
                Books = bookList,
                BookCategories = categories,
            };

            return this.View(viewModel);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult GetBookCoverImage(string id)
        {
            var book = this.books.GetById(id);
            var bookCover = book.Cover;
            var contentType = "image/jpeg";
            if (bookCover != null)
            {
                return this.File(bookCover, contentType);
            }
            else
            {
                return null;
            }
        }

        public ActionResult ByChapter(string bookId, string chapter)
        {
            var book = this.books.GetById(bookId);

            int navPage = this.pages.ChapterFirstPage(book, chapter);

            return this.RedirectToAction("ById", new { id = bookId, absolutePageNumber = navPage });
        }

    }
}

Web/MvcTemplate.Web/Controllers/UserController.cs
namespace MvcTemplate.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using MvcTemplate.Common.Mapping;
    using MvcTemplate.Data.Models;
    using MvcTemplate.Services.Data;
    using MvcTemplate.Web.ViewModels.Home;

    [Authorize]
    public class UserController : Controller
    {
        private IUserService users;
        private IBookService books;

        public UserController(IUserService users, IBookService books)
        {
            this.users = users;
            this.books = books;
        }

        [HttpGet]
        public ActionResult MyShelf()
        {
            var currentUser = this.users.UserByName(this.User.Identity.Name);

            var viewModel = new BookShelfViewModel()
            {
                BooksOnShelf = this.users.BooksOnShelf(currentUser).To<BookViewModel>().ToList(),
            };

            return this.View(viewModel);
        }

        public ActionResult AddToMyShelf(string bookId)
        {
            var currentUser = this.users.UserByName(this.User.Identity.Name);
            var book = this.books.GetById(bookId);
            var check = this.users.IsBookOnShelf(book, currentUser);
            if (check)
            {
                this.ViewBag.Message = "Err! Book is already on shelf!";
            }
            else
            {
                this.users.AddToShelf(book, currentUser);
                this.ViewBag.Message = "Book successfully added to shelf!";
            }

            return this.RedirectToAction("MyShelf");
        }

        public ActionResult RemoveFromShelf(string bookId)
        {
            var currentUser = this.users.UserByName(this.User.Identity.Name);
            var book = this.books.GetById(bookId);
            var check = this.users.IsBookOnShelf(book, currentUser);

            if (check)
            {
                this.users.RemoveFromShelf(book, currentUser);
                this.ViewBag.Message = "Book is successfully removed from shelf!";
            }
            else
            {
                this.ViewBag.Message = "Err! Book is not on shelf!";
            }

            return this.RedirectToAction("MyShelf");
        }
    }
}

Web/MvcTemplate.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@(this.ViewBag.Title) - ReadIt v1.0</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/Style.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        @(this.Html.ActionLink("ReadIt v1.0", "Index", "Home", new { area = string.Empty }, new { @class = "navbar-brand" }))
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">@(this.Html.ActionLink("Home", "Index", "Home", new { area = string.Empty }, new { title = "Home Page", @class = "nav-link" }))</li>
                <li class="nav-item active">@(this.Html.ActionLink("All Books", "AllBooks", "Books", new { area = string.Empty }, new { title = "All Books", @class = "nav-link" }))</li>
                @if (Request.IsAuthenticated)
                {
                    <li class="nav-item active">@(this.Html.ActionLink("My Shelf", "MyShelf", "User", new { area = string.Empty }, new  {title = "My Shelf", @class = "nav-link" }))</li>
                }

            </ul>
            @(this.Html.Partial("_LoginPartial"))
        </div>
    </nav>

    <main role="main">
        <div style="background:background-color">
            @(this.RenderBody())
        </div>
        <hr />
    </main>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @(this.RenderSection("scripts", required: false))
</body>
</html>