Web/MvcTemplate.Web/ViewModels/Home/UploadBookViewModel.cs
namespace MvcTemplate.Web.ViewModels.Home
{
    using System.Collections.Generic;

    public class UploadBookViewModel
    {
        public List<BookCategoryViewModel> Categories { get; set; }
    }
}

Web/MvcTemplate.Web/Controllers/UploadController.cs
namespace MvcTemplate.Web.Controllers
{
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using MvcTemplate.Common;
    using MvcTemplate.Common.Mapping;
    using MvcTemplate.Services.Data;
    using MvcTemplate.Web.ViewModels.Home;

    public class UploadController : BaseController
    {
        private IUploadBookService uploads;
        private ICategoryService categories;

        public UploadController(
            IUploadBookService uploads,
            ICategoryService categories)
        {
            this.uploads = uploads;
            this.categories = categories;
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public ActionResult UploadBook(HttpPostedFileBase file, string category, string language)
        {
            var uploadStatus = this.uploads.UploadFile(file, category, language);

            this.ViewBag.Message = uploadStatus;
            return this.View();
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public ActionResult UploadBook()
        {
            var allCategories = this.categories.GetAll().To<BookCategoryViewModel>().ToList();
            var viewModel = new UploadBookViewModel()
            {
                Categories = allCategories,
            };

            return this.View(viewModel);
        }
    }
}

Web/MvcTemplate.Web/Views/Upload/Test.cshtml
@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Test</h2>
<div>
    @Html.Raw(ViewBag.Message)
    @*@ViewBag.Message*@
</div>

Web/MvcTemplate.Web/Views/Upload/UploadBook.cshtml
@model MvcTemplate.Web.ViewModels.Home.UploadBookViewModel
    <div class="container">
        <h2>Book Upload</h2>
        @using (Html.BeginForm("UploadBook",
                                "Upload",
                                FormMethod.Post,
                                new { enctype = "multipart/form-data" }))
        {
            <br>
            var categories = MvcTemplate.Common.GlobalConstants.basicBookCategories;
            @ViewBag.Message

            <div class="row lg-8 ml-0 p-0">
                <div class="card mb-3 col-4 p-0">
                    <div class="card-header bg-dark text-white">Upload book</div>
                    <div class="card-body bg-light">
                        <div>
                            <label for="file">Select .epub file:</label>
                            <input type="file" name="File" id="file" required />
                        </div>
                    </div>
                </div>
                <div class="col-1"></div>
                <div class="form-group card col-3 p-0">
                    <label for="select" class="control-label card-header">Language:</label>
                    <div class="card-body">
                        <select class="form-control" id="select" name="Language">
                            <option value="English">English</option>
                            <option value="Bulgarian">Bulgarian</option>
                            <option value="Other">Other</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="card mb-3 form-group p-0 col-lg-8">
                <label class="card-header control-label">Choose Category:</label>
                <div class="card-body">
                    <div class="align-self-center">
                        @for (int i = 0; i < categories.Length; i++)
                        {
                            if (i == 0)
                            {
                                <div class="radio col-sm-6 col-md-4 col-lg-3 d-inline-block top align-self-center">
                                    <label>
                                        <input type="radio" name="Category" id="categoryOption@(i)" value="@categories[i]" checked="">
                                        @categories[i]
                                    </label>
                                </div>
                            }
                            else
                            {
                                <div class="radio col-sm-6 col-md-4 col-lg-3 d-inline-block">
                                    <label>
                                        <input type="radio" name="Category" id="categoryOption@(i)" value="@categories[i]">
                                        @categories[i]
                                    </label>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
            <div class="col-lg-offset-2">
                <button type="reset" class="btn btn-default">Cancel</button>
                <button type="submit" class="btn btn-primary">Upload</button>
            </div>

        }
    </div>